openapi: 3.0.2
info:
  title: Example API
  description: This is a sample API to demonstrate OpenAPI specification.
  version: 1.0.0
  contact:
    name: API Support
    url: https://example.com/support
    email: support@example.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server
  - url: http://localhost

tags:
  - name: Users
    description: User management operations

paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      operationId: getUsers
      description: Retrieve a list of all users.
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Users
      summary: Create a new user
      operationId: createUser
      description: Add a new user to the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users/{id}:
    get:
      tags:
        - Users
      summary: Get a user by ID
      operationId: getUserById
      description: Retrieve a user by their unique ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Users
      summary: Update a user
      operationId: updateUser
      description: Update the information of an existing user by ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUser'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Users
      summary: Delete a user
      operationId: deleteUser
      description: Delete an existing user by ID.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the user
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the user
        name:
          type: string
          description: The user's name
        email:
          type: string
          description: The user's email address
        createdAt:
          type: string
          format: date-time
          description: The date and time the user was created
    NewUser:
      type: object
      required:
        - id
        - name
        - email
      properties:
        id:
          type: string
          description: The unique identifier for the user
        name:
          type: string
          description: The user's name
        email:
          type: string
          description: The user's email address
        createdAt:
          type: string
          format: date-time
          description: The creation timestamp (optional)
    UpdateUser:
      type: object
      properties:
        name:
          type: string
          description: The user's name
        email:
          type: string
          description: The user's email address
    Error:
      type: object
      required:
        - message
        - status
      properties:
        message:
          type: string
          description: Error message describing what went wrong
          example: 'User not found'
        status:
          type: integer
          description: HTTP status code
          example: 404
        timestamp:
          type: string
          format: date-time
          description: When the error occurred
          example: '2025-07-15T17:30:00.000Z'
        path:
          type: string
          description: The API endpoint that generated the error
          example: '/users/123'
    ValidationError:
      type: object
      required:
        - message
        - status
        - errors
      properties:
        message:
          type: string
          description: General validation error message
          example: 'Validation failed'
        status:
          type: integer
          description: HTTP status code
          example: 400
        timestamp:
          type: string
          format: date-time
          description: When the error occurred
          example: '2025-07-15T17:30:00.000Z'
        path:
          type: string
          description: The API endpoint that generated the error
          example: '/users'
        errors:
          type: array
          description: List of specific validation errors
          items:
            type: object
            properties:
              field:
                type: string
                description: The field that failed validation
                example: 'email'
              message:
                type: string
                description: The validation error message
                example: 'Email is required'
              value:
                type: string
                description: The invalid value provided
                example: ''
    SuccessMessage:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: Success message
          example: 'User deleted successfully'
        timestamp:
          type: string
          format: date-time
          description: When the operation was completed
          example: '2025-07-15T17:30:00.000Z'
